# ----------------
# GOOGLE DISTROLESS WITH SSL
# ----------------
FROM gcr.io/distroless/static-debian13:nonroot

# Path INSIDE the build context, passed by build arg
ARG BIN_PATH=dist/myapp

COPY ${BIN_PATH} /myapp

EXPOSE 3005

USER nonroot:nonroot

CMD ["./main"]
